version: '3.8'
services:
  portalservice:
    build: .
    container_name: portalservice
    hostname: portalservice
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: unless-stopped
    depends_on: 
      - portal
  portal:
    image: mongo:latest
    container_name: portal
    hostname: portal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: portal
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata: