name: CD

on:
  # workflow_run:
  #   workflows: ['CI']
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      APP_NAME: ms-portal-bank
      APP_PORT: 3000
      APP_NETWORK: app-network

    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Get commit
        id: git
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      
      - name: Get latest version
        id: version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Git
        run: |
          echo Branch name is: ${{ github.ref_name }}
          echo Short sha: ${{ steps.git.outputs.short_sha}}
          echo Version is: ${{ steps.version.outputs.current-version}}

      - name: Environment
        run: |
          echo APP_NAME is: ${{ env.APP_NAME}}
          echo APP_PORT is: ${{ env.APP_PORT}}
          echo APP_NETWORK is: ${{ env.APP_NETWORK}}

      - name: Build a Node.js project with Yarn
        run: |
            yarn install
            yarn run build:production
